import { NextRequest, NextResponse } from "next/server";
import { sendEmail, sendAccessRequestConfirmation } from "../../lib/email";

const ADMIN_EMAIL = "kamalandshrestha@gmail.com";

export async function POST(req: NextRequest) {
  try {
    const { email, message } = await req.json();

    if (!email) {
      return NextResponse.json(
        { error: "Email is required" },
        { status: 400 }
      );
    }

    // Send notification email to admin
    const subject = `New Access Request - ${email}`;
    
    const html = `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; background-color: #f9fafb; padding: 20px;">
        <div style="background-color: white; border-radius: 16px; padding: 40px; box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);">
          <!-- Header -->
          <div style="text-align: center; margin-bottom: 30px;">
            <h1 style="color: #1f2937; margin: 0; font-size: 28px; font-weight: bold;">
              🔐 New Access Request
            </h1>
            <p style="color: #6b7280; margin: 10px 0 0 0; font-size: 16px;">
              Someone has requested access to your application
            </p>
          </div>

          <!-- Request Details -->
          <div style="background-color: #f3f4f6; border-radius: 12px; padding: 24px; margin-bottom: 25px;">
            <h2 style="color: #1f2937; font-size: 20px; margin-bottom: 20px; margin-top: 0;">
              Request Details
            </h2>
            
            <div style="margin-bottom: 15px;">
              <strong style="color: #1f2937; display: block; margin-bottom: 5px;">Email Address:</strong>
              <span style="color: #4b5563; font-size: 16px; background-color: white; padding: 8px 12px; border-radius: 6px; display: inline-block;">
                ${email}
              </span>
            </div>
            
            <div style="margin-bottom: 15px;">
              <strong style="color: #1f2937; display: block; margin-bottom: 5px;">Timestamp:</strong>
              <span style="color: #6b7280; font-size: 14px;">
                ${new Date().toLocaleString()}
              </span>
            </div>
            
            ${message ? `
            <div>
              <strong style="color: #1f2937; display: block; margin-bottom: 5px;">Message:</strong>
              <div style="color: #4b5563; font-size: 16px; background-color: white; padding: 12px; border-radius: 6px; line-height: 1.5;">
                ${message}
              </div>
            </div>
            ` : `
            <div>
              <span style="color: #6b7280; font-style: italic;">No additional message provided</span>
            </div>
            `}
          </div>

          <!-- Action Required -->
          <div style="background-color: #fef3c7; border: 1px solid #f59e0b; border-radius: 8px; padding: 16px; margin-bottom: 25px;">
            <h3 style="color: #92400e; margin: 0 0 8px 0; font-size: 16px;">
              ⚠️ Action Required
            </h3>
            <p style="color: #92400e; margin: 0; font-size: 14px;">
              Please review this request and add the email to your whitelist if you want to grant access.
            </p>
          </div>

          <!-- Instructions -->
          <div style="margin-bottom: 30px;">
            <h3 style="color: #1f2937; font-size: 18px; margin-bottom: 15px;">
              To Grant Access:
            </h3>
            <ol style="color: #4b5563; font-size: 14px; line-height: 1.6; padding-left: 20px;">
              <li style="margin-bottom: 8px;">Open your <code style="background-color: #f3f4f6; padding: 2px 6px; border-radius: 4px;">auth.ts</code> file</li>
              <li style="margin-bottom: 8px;">Add <code style="background-color: #f3f4f6; padding: 2px 6px; border-radius: 4px;">"${email}"</code> to the <code style="background-color: #f3f4f6; padding: 2px 6px; border-radius: 4px;">WHITELISTED_EMAILS</code> array</li>
              <li style="margin-bottom: 8px;">Deploy your changes</li>
              <li>Notify the user that access has been granted</li>
            </ol>
          </div>

          <!-- Footer -->
          <div style="border-top: 1px solid #e5e7eb; padding-top: 20px; text-align: center;">
            <p style="color: #9ca3af; font-size: 12px; margin: 0;">
              This notification was automatically generated by your MoneyManager application.
            </p>
          </div>
        </div>
      </div>
    `;

    const text = `
      New Access Request

      Email: ${email}
      Timestamp: ${new Date().toLocaleString()}
      ${message ? `Message: ${message}` : 'No additional message provided'}

      To grant access:
      1. Open your auth.ts file
      2. Add "${email}" to the WHITELISTED_EMAILS array
      3. Deploy your changes
      4. Notify the user that access has been granted

      This notification was automatically generated by your MoneyManager application.
    `;

    // Send notification email to admin
    const adminEmailResult = await sendEmail({
      to: ADMIN_EMAIL,
      subject,
      text,
      html
    });

    // Send confirmation email to the user
    const userEmailResult = await sendAccessRequestConfirmation(email, message);

    if (adminEmailResult.success) {
      // Don't fail the request if user confirmation email fails
      if (!userEmailResult.success) {
        console.warn("Failed to send confirmation email to user:", userEmailResult.error);
      }
      
      return NextResponse.json({
        success: true,
        message: "Access request submitted successfully"
      });
    } else {
      console.error("Failed to send admin notification email:", adminEmailResult.error);
      return NextResponse.json(
        { error: "Failed to send request. Please try again." },
        { status: 500 }
      );
    }

  } catch (error) {
    console.error("Error processing access request:", error);
    return NextResponse.json(
      { error: "Internal server error" },
      { status: 500 }
    );
  }
} 