CREATE TYPE "CategoryType" AS ENUM (
  'EXPENSE',
  'INCOME'
);

CREATE TYPE "RecurringFrequency" AS ENUM (
  'DAILY',
  'WEEKLY',
  'MONTHLY',
  'YEARLY'
);

CREATE TYPE "InvestmentType" AS ENUM (
  'STOCKS',
  'CRYPTO',
  'MUTUAL_FUNDS',
  'BONDS',
  'REAL_ESTATE',
  'GOLD',
  'FIXED_DEPOSIT',
  'PROVIDENT_FUNDS',
  'SAFE_KEEPINGS',
  'EMERGENCY_FUND',
  'MARRIAGE',
  'VACATION',
  'OTHER'
);

CREATE TYPE "BudgetPeriod" AS ENUM (
  'WEEKLY',
  'MONTHLY',
  'QUARTERLY',
  'YEARLY'
);

CREATE TYPE "DebtStatus" AS ENUM (
  'ACTIVE',
  'PARTIALLY_PAID',
  'FULLY_PAID',
  'OVERDUE',
  'DEFAULTED'
);

CREATE TYPE "SubscriptionStatus" AS ENUM (
  'ACTIVE',
  'INACTIVE',
  'UNSUBSCRIBED',
  'BOUNCED'
);

CREATE TYPE "LoanStatus" AS ENUM (
  'ACTIVE',
  'PARTIALLY_PAID',
  'FULLY_PAID',
  'OVERDUE',
  'DEFAULTED'
);

CREATE TYPE "NotificationType" AS ENUM (
  'LOW_BALANCE',
  'DUE_DATE_REMINDER',
  'SPENDING_ALERT',
  'INVESTMENT_MATURITY',
  'DEBT_REMINDER',
  'LOAN_REMINDER',
  'PASSWORD_EXPIRY',
  'MONTHLY_SUMMARY',
  'PASSWORD_SHARED'
);

CREATE TYPE "NotificationPriority" AS ENUM (
  'LOW',
  'NORMAL',
  'HIGH',
  'URGENT'
);

CREATE TYPE "ActivityAction" AS ENUM (
  'CREATE',
  'UPDATE',
  'DELETE',
  'READ',
  'BULK_CREATE',
  'BULK_UPDATE',
  'BULK_DELETE',
  'BULK_IMPORT',
  'EXPORT',
  'LOGIN',
  'LOGOUT',
  'SHARE',
  'SYNC',
  'CALCULATE',
  'GENERATE',
  'SEND'
);

CREATE TYPE "ActivityEntityType" AS ENUM (
  'EXPENSE',
  'INCOME',
  'INVESTMENT',
  'DEBT',
  'LOAN',
  'ACCOUNT',
  'CATEGORY',
  'BUDGET_TARGET',
  'DEBT_REPAYMENT',
  'LOAN_REPAYMENT',
  'USER',
  'USER_PROFILE',
  'USER_SETTINGS',
  'NOTIFICATION',
  'PASSWORD',
  'BOOKMARK',
  'EMERGENCY_EMAIL',
  'PASSWORD_SHARE',
  'REPORT',
  'EXPORT',
  'IMPORT',
  'SESSION',
  'AUTHENTICATION',
  'NET_WORTH_INCLUSION',
  'SYSTEM',
  'CRON_JOB',
  'NOTE'
);

CREATE TYPE "ActivityCategory" AS ENUM (
  'TRANSACTION',
  'ACCOUNT',
  'INVESTMENT',
  'DEBT_LOAN',
  'AUTHENTICATION',
  'SECURITY',
  'NOTIFICATION',
  'BUDGET',
  'REPORT',
  'SYSTEM',
  'USER_MANAGEMENT',
  'BULK_OPERATION',
  'NOTE'
);

CREATE TYPE "ActivitySeverity" AS ENUM (
  'DEBUG',
  'INFO',
  'WARNING',
  'ERROR',
  'CRITICAL'
);

CREATE TYPE "ActivityStatus" AS ENUM (
  'SUCCESS',
  'FAILED',
  'ERROR',
  'PARTIAL',
  'PENDING'
);

CREATE TYPE "WorthEntityType" AS ENUM (
  'ACCOUNT',
  'INVESTMENT',
  'DEBT'
);

CREATE TYPE "PasswordShareReason" AS ENUM (
  'INACTIVITY',
  'MANUAL'
);

CREATE TYPE "LiquidityTimeframe" AS ENUM (
  'IMMEDIATE',
  'DAYS',
  'WEEKS',
  'MONTHS',
  'YEARS'
);

CREATE TYPE "RiskLevel" AS ENUM (
  'VERY_LOW',
  'LOW',
  'MEDIUM',
  'HIGH',
  'VERY_HIGH'
);

CREATE TYPE "ChatSender" AS ENUM (
  'USER',
  'ASSISTANT'
);

CREATE TYPE "ChatMessageType" AS ENUM (
  'TEXT',
  'IMAGE',
  'FILE',
  'SYSTEM',
  'ERROR'
);

CREATE TYPE "ChatFeedback" AS ENUM (
  'LIKE',
  'DISLIKE'
);

CREATE TABLE "User" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar UNIQUE,
  "name" varchar,
  "number" varchar UNIQUE NOT NULL,
  "password" varchar NOT NULL,
  "profilePictureUrl" varchar,
  "createdAt" timestamp DEFAULT (now()),
  "updatedAt" timestamp DEFAULT (now()),
  "currency" varchar DEFAULT 'USD',
  "timezone" varchar DEFAULT 'UTC'
);

CREATE TABLE "Account" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "holderName" varchar NOT NULL,
  "accountNumber" varchar UNIQUE NOT NULL,
  "branchCode" varchar NOT NULL,
  "bankName" varchar NOT NULL,
  "branchName" varchar NOT NULL,
  "bankAddress" varchar NOT NULL,
  "accountType" varchar NOT NULL,
  "mobileNumbers" varchar[] NOT NULL,
  "branchContacts" varchar[] NOT NULL,
  "swift" varchar NOT NULL,
  "bankEmail" varchar NOT NULL,
  "accountOpeningDate" timestamp NOT NULL,
  "securityQuestion" varchar[] NOT NULL,
  "userId" integer NOT NULL,
  "balance" decimal DEFAULT 0,
  "createdAt" timestamp DEFAULT (now()),
  "updatedAt" timestamp DEFAULT (now()),
  "appPassword" varchar,
  "appPin" varchar,
  "appUsername" varchar,
  "nickname" varchar,
  "notes" text,
  "isEmergencyFund" boolean DEFAULT false,
  "isLiquid" boolean DEFAULT true,
  "liquidityTimeframe" "LiquidityTimeframe" DEFAULT 'IMMEDIATE',
  "riskLevel" "RiskLevel" DEFAULT 'VERY_LOW'
);

CREATE TABLE "Category" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "type" "CategoryType" NOT NULL,
  "color" varchar DEFAULT '#6366f1',
  "icon" varchar,
  "createdAt" timestamp DEFAULT (now()),
  "updatedAt" timestamp DEFAULT (now()),
  "userId" integer NOT NULL,
  "includedInBudget" boolean DEFAULT true
);

CREATE TABLE "Expense" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar NOT NULL,
  "description" text,
  "amount" decimal NOT NULL,
  "date" timestamp DEFAULT (now()),
  "categoryId" integer NOT NULL,
  "accountId" integer,
  "userId" integer NOT NULL,
  "tags" varchar[] NOT NULL,
  "receipt" varchar,
  "isRecurring" boolean DEFAULT false,
  "recurringFrequency" "RecurringFrequency",
  "createdAt" timestamp DEFAULT (now()),
  "updatedAt" timestamp DEFAULT (now()),
  "notes" text,
  "location" varchar[] NOT NULL,
  "currency" varchar DEFAULT 'USD'
);

CREATE TABLE "Income" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar NOT NULL,
  "description" text,
  "amount" decimal NOT NULL,
  "date" timestamp DEFAULT (now()),
  "categoryId" integer NOT NULL,
  "accountId" integer,
  "userId" integer NOT NULL,
  "tags" varchar[] NOT NULL,
  "isRecurring" boolean DEFAULT false,
  "recurringFrequency" "RecurringFrequency",
  "createdAt" timestamp DEFAULT (now()),
  "updatedAt" timestamp DEFAULT (now()),
  "notes" text,
  "location" varchar[] NOT NULL,
  "currency" varchar DEFAULT 'USD'
);

CREATE TABLE "Investment" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "type" "InvestmentType" NOT NULL,
  "symbol" varchar,
  "quantity" decimal NOT NULL,
  "purchasePrice" decimal NOT NULL,
  "currentPrice" decimal DEFAULT 0,
  "purchaseDate" timestamp NOT NULL,
  "accountId" integer,
  "userId" integer NOT NULL,
  "notes" text,
  "createdAt" timestamp DEFAULT (now()),
  "updatedAt" timestamp DEFAULT (now()),
  "interestRate" decimal,
  "maturityDate" timestamp,
  "hasMaturityDate" boolean DEFAULT false,
  "isInflationHedge" boolean DEFAULT false,
  "isLiquid" boolean DEFAULT false,
  "liquidityTimeframe" "LiquidityTimeframe" DEFAULT 'DAYS',
  "riskLevel" "RiskLevel" DEFAULT 'MEDIUM',
  "deductFromAccount" boolean DEFAULT true
);

CREATE TABLE "InvestmentTarget" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "investmentType" "InvestmentType" NOT NULL,
  "targetAmount" decimal NOT NULL,
  "userId" integer NOT NULL,
  "createdAt" timestamp DEFAULT (now()),
  "updatedAt" timestamp DEFAULT (now()),
  "targetCompletionDate" timestamp,
  "nickname" varchar
);

CREATE TABLE "BudgetTarget" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "targetAmount" decimal NOT NULL,
  "currentAmount" decimal DEFAULT 0,
  "period" "BudgetPeriod" NOT NULL,
  "startDate" timestamp NOT NULL,
  "endDate" timestamp NOT NULL,
  "userId" integer NOT NULL,
  "isActive" boolean DEFAULT true,
  "createdAt" timestamp DEFAULT (now()),
  "updatedAt" timestamp DEFAULT (now())
);

CREATE TABLE "Debt" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "borrowerName" varchar NOT NULL,
  "borrowerContact" varchar,
  "borrowerEmail" varchar,
  "amount" decimal NOT NULL,
  "interestRate" decimal DEFAULT 0,
  "dueDate" timestamp,
  "lentDate" timestamp DEFAULT (now()),
  "status" "DebtStatus" DEFAULT 'ACTIVE',
  "purpose" text,
  "notes" text,
  "userId" integer NOT NULL,
  "createdAt" timestamp DEFAULT (now()),
  "updatedAt" timestamp DEFAULT (now()),
  "accountId" integer,
  "borrowerCreditRating" varchar,
  "hasCollateral" boolean DEFAULT false,
  "isLiquid" boolean DEFAULT false,
  "liquidityTimeframe" "LiquidityTimeframe" DEFAULT 'MONTHS',
  "riskLevel" "RiskLevel" DEFAULT 'MEDIUM'
);

CREATE TABLE "DebtRepayment" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "amount" decimal NOT NULL,
  "repaymentDate" timestamp DEFAULT (now()),
  "notes" text,
  "debtId" integer NOT NULL,
  "createdAt" timestamp DEFAULT (now()),
  "updatedAt" timestamp DEFAULT (now()),
  "accountId" integer
);

CREATE TABLE "Bookmark" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar NOT NULL,
  "url" varchar NOT NULL,
  "description" text,
  "category" varchar,
  "favicon" varchar,
  "tags" varchar[] NOT NULL,
  "userId" integer NOT NULL,
  "createdAt" timestamp DEFAULT (now()),
  "updatedAt" timestamp DEFAULT (now())
);

CREATE TABLE "Subscriber" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar UNIQUE NOT NULL,
  "name" varchar,
  "phone" varchar,
  "status" "SubscriptionStatus" DEFAULT 'ACTIVE',
  "subscribedAt" timestamp DEFAULT (now()),
  "unsubscribedAt" timestamp,
  "newsletterEnabled" boolean DEFAULT true,
  "marketingEnabled" boolean DEFAULT false,
  "productUpdatesEnabled" boolean DEFAULT true,
  "weeklyDigestEnabled" boolean DEFAULT true,
  "source" varchar,
  "tags" varchar[] NOT NULL,
  "lastEngagementAt" timestamp,
  "createdAt" timestamp DEFAULT (now()),
  "updatedAt" timestamp DEFAULT (now())
);

CREATE TABLE "WhitelistedEmail" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar UNIQUE NOT NULL,
  "addedBy" varchar,
  "reason" text,
  "isActive" boolean DEFAULT true,
  "createdAt" timestamp DEFAULT (now()),
  "updatedAt" timestamp DEFAULT (now())
);

CREATE TABLE "Loan" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "lenderName" varchar NOT NULL,
  "lenderContact" varchar,
  "lenderEmail" varchar,
  "amount" decimal NOT NULL,
  "interestRate" decimal DEFAULT 0,
  "dueDate" timestamp,
  "takenDate" timestamp DEFAULT (now()),
  "status" "LoanStatus" DEFAULT 'ACTIVE',
  "purpose" text,
  "notes" text,
  "accountId" integer,
  "userId" integer NOT NULL,
  "createdAt" timestamp DEFAULT (now()),
  "updatedAt" timestamp DEFAULT (now())
);

CREATE TABLE "LoanRepayment" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "amount" decimal NOT NULL,
  "repaymentDate" timestamp DEFAULT (now()),
  "notes" text,
  "loanId" integer NOT NULL,
  "accountId" integer,
  "createdAt" timestamp DEFAULT (now()),
  "updatedAt" timestamp DEFAULT (now())
);

CREATE TABLE "Password" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "websiteName" varchar NOT NULL,
  "username" varchar NOT NULL,
  "passwordHash" varchar NOT NULL,
  "notes" text,
  "favicon" varchar,
  "category" varchar,
  "tags" varchar[] NOT NULL,
  "userId" integer NOT NULL,
  "createdAt" timestamp DEFAULT (now()),
  "updatedAt" timestamp DEFAULT (now()),
  "transactionPin" varchar,
  "validity" timestamp,
  "description" text NOT NULL
);

CREATE TABLE "Notification" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar NOT NULL,
  "message" text NOT NULL,
  "type" "NotificationType" NOT NULL,
  "priority" "NotificationPriority" DEFAULT 'NORMAL',
  "isRead" boolean DEFAULT false,
  "actionUrl" varchar,
  "metadata" json,
  "userId" integer NOT NULL,
  "createdAt" timestamp DEFAULT (now()),
  "updatedAt" timestamp DEFAULT (now())
);

CREATE TABLE "DismissedNotification" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId" integer NOT NULL,
  "notificationType" "NotificationType" NOT NULL,
  "entityId" varchar NOT NULL,
  "dismissedAt" timestamp DEFAULT (now())
);

CREATE TABLE "NotificationSettings" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "lowBalanceEnabled" boolean DEFAULT true,
  "lowBalanceThreshold" decimal DEFAULT 500,
  "dueDateEnabled" boolean DEFAULT true,
  "dueDateDaysBefore" integer DEFAULT 7,
  "spendingAlertsEnabled" boolean DEFAULT true,
  "monthlySpendingLimit" decimal DEFAULT 5000,
  "investmentAlertsEnabled" boolean DEFAULT true,
  "emailNotifications" boolean DEFAULT false,
  "pushNotifications" boolean DEFAULT true,
  "userId" integer UNIQUE NOT NULL,
  "createdAt" timestamp DEFAULT (now()),
  "updatedAt" timestamp DEFAULT (now()),
  "highValueIncomeThreshold" decimal DEFAULT 50000,
  "highValueExpenseThreshold" decimal DEFAULT 10000,
  "autoBookmarkEnabled" boolean DEFAULT true
);

CREATE TABLE "AccountThreshold" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "accountId" integer NOT NULL,
  "lowBalanceThreshold" decimal DEFAULT 500,
  "userId" integer NOT NULL,
  "createdAt" timestamp DEFAULT (now()),
  "updatedAt" timestamp DEFAULT (now())
);

CREATE TABLE "TransactionBookmark" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "transactionType" varchar NOT NULL,
  "transactionId" integer NOT NULL,
  "title" varchar NOT NULL,
  "description" text,
  "notes" text,
  "tags" varchar[] NOT NULL,
  "userId" integer NOT NULL,
  "createdAt" timestamp DEFAULT (now()),
  "updatedAt" timestamp DEFAULT (now())
);

CREATE TABLE "UserCheckin" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId" integer NOT NULL,
  "checkinAt" timestamp DEFAULT (now()),
  "ipAddress" varchar,
  "userAgent" text
);

CREATE TABLE "EmergencyEmail" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar NOT NULL,
  "label" varchar,
  "userId" integer NOT NULL,
  "isActive" boolean DEFAULT true,
  "createdAt" timestamp DEFAULT (now()),
  "updatedAt" timestamp DEFAULT (now())
);

CREATE TABLE "PasswordShare" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId" integer NOT NULL,
  "recipientEmail" varchar NOT NULL,
  "sentAt" timestamp DEFAULT (now()),
  "passwordCount" integer NOT NULL,
  "shareReason" "PasswordShareReason" DEFAULT 'INACTIVITY',
  "secretKey" varchar,
  "expiresAt" timestamp
);

CREATE TABLE "NetWorthInclusion" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId" integer NOT NULL,
  "entityType" "WorthEntityType" NOT NULL,
  "entityId" integer NOT NULL,
  "includeInNetWorth" boolean DEFAULT true,
  "createdAt" timestamp DEFAULT (now()),
  "updatedAt" timestamp DEFAULT (now())
);

CREATE TABLE "ActivityLog" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId" integer,
  "action" "ActivityAction" NOT NULL,
  "entityType" "ActivityEntityType" NOT NULL,
  "entityId" integer,
  "description" text NOT NULL,
  "metadata" json,
  "ipAddress" varchar,
  "userAgent" text,
  "sessionId" varchar,
  "category" "ActivityCategory" DEFAULT 'TRANSACTION',
  "severity" "ActivitySeverity" DEFAULT 'INFO',
  "status" "ActivityStatus" DEFAULT 'SUCCESS',
  "errorMessage" text,
  "duration" integer,
  "createdAt" timestamp DEFAULT (now())
);

CREATE TABLE "Note" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar NOT NULL,
  "content" text,
  "color" varchar DEFAULT '#fbbf24',
  "isPinned" boolean DEFAULT false,
  "isArchived" boolean DEFAULT false,
  "tags" varchar[] NOT NULL,
  "relatedExpenseId" integer,
  "relatedIncomeId" integer,
  "relatedInvestmentId" integer,
  "relatedDebtId" integer,
  "relatedLoanId" integer,
  "relatedAccountId" integer,
  "amount" decimal,
  "currency" varchar DEFAULT 'USD',
  "noteDate" timestamp,
  "reminderDate" timestamp,
  "userId" integer NOT NULL,
  "createdAt" timestamp DEFAULT (now()),
  "updatedAt" timestamp DEFAULT (now())
);

CREATE TABLE "ChatThread" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar NOT NULL,
  "description" text,
  "isActive" boolean DEFAULT true,
  "isPinned" boolean DEFAULT false,
  "lastMessageAt" timestamp DEFAULT (now()),
  "userId" integer NOT NULL,
  "createdAt" timestamp DEFAULT (now()),
  "updatedAt" timestamp DEFAULT (now())
);

CREATE TABLE "ChatConversation" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "content" text NOT NULL,
  "sender" "ChatSender" NOT NULL,
  "messageType" "ChatMessageType" DEFAULT 'TEXT',
  "isProcessing" boolean DEFAULT false,
  "processingSteps" integer DEFAULT 0,
  "attachments" json,
  "threadId" integer NOT NULL,
  "createdAt" timestamp DEFAULT (now()),
  "updatedAt" timestamp DEFAULT (now()),
  "comments" text,
  "feedback" "ChatFeedback",
  "responseTimeSeconds" float,
  "tokenCount" integer,
  "inputTokens" integer,
  "intermediateSteps" json,
  "outputTokens" integer,
  "systemPrompt" json
);

CREATE UNIQUE INDEX ON "InvestmentTarget" ("userId", "investmentType");

CREATE INDEX ON "InvestmentTarget" ("userId");

CREATE INDEX ON "DismissedNotification" ("userId", "notificationType");

CREATE UNIQUE INDEX ON "DismissedNotification" ("userId", "notificationType", "entityId");

CREATE UNIQUE INDEX ON "AccountThreshold" ("accountId", "userId");

CREATE INDEX ON "AccountThreshold" ("userId");

CREATE UNIQUE INDEX ON "TransactionBookmark" ("transactionType", "transactionId", "userId");

CREATE INDEX ON "UserCheckin" ("userId", "checkinAt");

CREATE UNIQUE INDEX ON "EmergencyEmail" ("userId", "email");

CREATE INDEX ON "EmergencyEmail" ("userId");

CREATE INDEX ON "PasswordShare" ("userId", "sentAt");

CREATE UNIQUE INDEX ON "NetWorthInclusion" ("userId", "entityType", "entityId");

CREATE INDEX ON "NetWorthInclusion" ("userId", "entityType");

CREATE INDEX ON "NetWorthInclusion" ("userId", "includeInNetWorth");

CREATE INDEX ON "ActivityLog" ("userId", "createdAt");

CREATE INDEX ON "ActivityLog" ("entityType", "action");

CREATE INDEX ON "ActivityLog" ("category", "createdAt");

CREATE INDEX ON "ActivityLog" ("status", "severity");

CREATE INDEX ON "ActivityLog" ("createdAt");

CREATE INDEX ON "Note" ("userId", "isPinned");

CREATE INDEX ON "Note" ("userId", "isArchived");

CREATE INDEX ON "Note" ("userId", "createdAt");

CREATE INDEX ON "Note" ("userId", "reminderDate");

CREATE INDEX ON "ChatThread" ("userId", "lastMessageAt");

CREATE INDEX ON "ChatThread" ("userId", "isPinned");

CREATE INDEX ON "ChatThread" ("userId", "isActive");

CREATE INDEX ON "ChatConversation" ("threadId", "createdAt");

CREATE INDEX ON "ChatConversation" ("sender", "createdAt");

CREATE INDEX ON "ChatConversation" ("feedback");

COMMENT ON COLUMN "NotificationSettings"."userId" IS 'One-to-one relationship with User';

COMMENT ON COLUMN "NotificationSettings"."highValueIncomeThreshold" IS 'Auto-bookmark threshold for income';

COMMENT ON COLUMN "NotificationSettings"."highValueExpenseThreshold" IS 'Auto-bookmark threshold for expenses';

COMMENT ON COLUMN "NotificationSettings"."autoBookmarkEnabled" IS 'Enable auto-bookmarking for high-value transactions';

COMMENT ON COLUMN "TransactionBookmark"."transactionType" IS 'INCOME or EXPENSE';

ALTER TABLE "Account" ADD FOREIGN KEY ("userId") REFERENCES "User" ("id");

ALTER TABLE "Category" ADD FOREIGN KEY ("userId") REFERENCES "User" ("id");

ALTER TABLE "Expense" ADD FOREIGN KEY ("categoryId") REFERENCES "Category" ("id");

ALTER TABLE "Expense" ADD FOREIGN KEY ("accountId") REFERENCES "Account" ("id");

ALTER TABLE "Expense" ADD FOREIGN KEY ("userId") REFERENCES "User" ("id");

ALTER TABLE "Income" ADD FOREIGN KEY ("categoryId") REFERENCES "Category" ("id");

ALTER TABLE "Income" ADD FOREIGN KEY ("accountId") REFERENCES "Account" ("id");

ALTER TABLE "Income" ADD FOREIGN KEY ("userId") REFERENCES "User" ("id");

ALTER TABLE "Investment" ADD FOREIGN KEY ("accountId") REFERENCES "Account" ("id");

ALTER TABLE "Investment" ADD FOREIGN KEY ("userId") REFERENCES "User" ("id");

ALTER TABLE "InvestmentTarget" ADD FOREIGN KEY ("userId") REFERENCES "User" ("id");

ALTER TABLE "BudgetTarget" ADD FOREIGN KEY ("userId") REFERENCES "User" ("id");

ALTER TABLE "Debt" ADD FOREIGN KEY ("userId") REFERENCES "User" ("id");

ALTER TABLE "Debt" ADD FOREIGN KEY ("accountId") REFERENCES "Account" ("id");

ALTER TABLE "DebtRepayment" ADD FOREIGN KEY ("debtId") REFERENCES "Debt" ("id");

ALTER TABLE "DebtRepayment" ADD FOREIGN KEY ("accountId") REFERENCES "Account" ("id");

ALTER TABLE "Bookmark" ADD FOREIGN KEY ("userId") REFERENCES "User" ("id");

ALTER TABLE "Loan" ADD FOREIGN KEY ("accountId") REFERENCES "Account" ("id");

ALTER TABLE "Loan" ADD FOREIGN KEY ("userId") REFERENCES "User" ("id");

ALTER TABLE "LoanRepayment" ADD FOREIGN KEY ("loanId") REFERENCES "Loan" ("id");

ALTER TABLE "LoanRepayment" ADD FOREIGN KEY ("accountId") REFERENCES "Account" ("id");

ALTER TABLE "Password" ADD FOREIGN KEY ("userId") REFERENCES "User" ("id");

ALTER TABLE "Notification" ADD FOREIGN KEY ("userId") REFERENCES "User" ("id");

ALTER TABLE "DismissedNotification" ADD FOREIGN KEY ("userId") REFERENCES "User" ("id");

ALTER TABLE "NotificationSettings" ADD FOREIGN KEY ("userId") REFERENCES "User" ("id");

ALTER TABLE "AccountThreshold" ADD FOREIGN KEY ("accountId") REFERENCES "Account" ("id");

ALTER TABLE "AccountThreshold" ADD FOREIGN KEY ("userId") REFERENCES "User" ("id");

ALTER TABLE "TransactionBookmark" ADD FOREIGN KEY ("userId") REFERENCES "User" ("id");

ALTER TABLE "UserCheckin" ADD FOREIGN KEY ("userId") REFERENCES "User" ("id");

ALTER TABLE "EmergencyEmail" ADD FOREIGN KEY ("userId") REFERENCES "User" ("id");

ALTER TABLE "PasswordShare" ADD FOREIGN KEY ("userId") REFERENCES "User" ("id");

ALTER TABLE "NetWorthInclusion" ADD FOREIGN KEY ("userId") REFERENCES "User" ("id");

ALTER TABLE "ActivityLog" ADD FOREIGN KEY ("userId") REFERENCES "User" ("id");

ALTER TABLE "Note" ADD FOREIGN KEY ("userId") REFERENCES "User" ("id");

ALTER TABLE "ChatThread" ADD FOREIGN KEY ("userId") REFERENCES "User" ("id");

ALTER TABLE "ChatConversation" ADD FOREIGN KEY ("threadId") REFERENCES "ChatThread" ("id");
